// The overworld: a single-screen, classic tile-grid map. No camera/scrolling —
// the whole map fits the viewport and the tile size scales to fit. Handles
// rendering, grid movement (keyboard + click-to-walk), collision, and
// interaction triggers (grass step, trainer/gym/mart bump, north exit). The
// chrome around the map is split into a top bar (money/balls · badges ·
// PC Box/Items/Exit), an always-on party bar down the right, and a bottom bar
// (route info · lobby code).
//
// It is deliberately engine-only: it owns no game rules. The host supplies a
// `state` object (current map/position/badges/beaten trainers …) which the
// overworld reads and writes, plus async `hooks` invoked on each interaction.
// While a hook runs, input is locked (`busy`) so battles/menus can take over
// the screen and resume cleanly afterwards.
import { spriteFront, TYPE_COLORS, expFraction } from './data.js';

const el = (tag, props = {}, kids = []) => {
  const n = document.createElement(tag);
  for (const [k, v] of Object.entries(props)) {
    if (k === 'class') n.className = v;
    else if (k === 'text') n.textContent = v;
    else if (k === 'html') n.innerHTML = v;
    else if (k.startsWith('on') && typeof v === 'function') n.addEventListener(k.slice(2), v);
    else if (v === true) n.setAttribute(k, '');
    else if (v !== false && v != null) n.setAttribute(k, v);
  }
  for (const c of [].concat(kids)) if (c != null) n.append(c);
  return n;
};

// Tile codes (must match scripts/build-world.mjs geometry).
const WALL = '#', FLOOR = '.', GRASS = 'G', TRAINER = 'T', MART = 'M',
  GYM_K = 'K', GYM_J = 'J', NORTH = 'N', SPAWN = 'S', BUILDING = 'B';
const WALKABLE = new Set([FLOOR, GRASS, NORTH, SPAWN]);

// Building sprites (generated by scripts/build-tiles.mjs). Each is anchored at
// its door tile and drawn over a 3x3 footprint, growing upward from the door.
const BUILDING_SPRITES = {
  mart: 'assets/tiles/mart.png',
  kanto: 'assets/tiles/gym-k.png',
  johto: 'assets/tiles/gym-j.png',
};

const DIRS = {
  up: { dx: 0, dy: -1 }, down: { dx: 0, dy: 1 },
  left: { dx: -1, dy: 0 }, right: { dx: 1, dy: 0 },
};
const KEY_DIR = {
  ArrowUp: 'up', ArrowDown: 'down', ArrowLeft: 'left', ArrowRight: 'right',
  w: 'up', s: 'down', a: 'left', d: 'right', W: 'up', S: 'down', A: 'left', D: 'right',
};
const STEP_MS = 300; // movement cadence; mirrored to CSS via --step-ms so the
                     // walk glide lasts exactly one step (half the old speed)
const HOP_MS = 200;  // walk-bounce duration — quicker than a full step, so the
                     // little hop reads as snappy (see hop() + the ow-hop keyframe)

// Overworld character sprite sheets (generated by scripts/build-characters.mjs).
// 32x48 atlas: rows = down/up/side, cols = walk frame A/B. Rendered as the
// actor body's background-image; facing/frame pick the cell in CSS.
const PLAYER_CHARS = new Set(['red', 'blue', 'green', 'gold', 'silver', 'kris']);
const NPC_VARIANTS = 4;
// Character sheets are applied via a CSS custom property (--sheet) consumed by an
// external stylesheet, where a relative url() would resolve against the .css file,
// not the page. Resolve to an absolute URL so it works at any base path.
const charSheet = (id) => new URL(`assets/characters/${PLAYER_CHARS.has(id) ? id : 'red'}.png`, document.baseURI).href;
// Deterministic NPC look per (map,id) so a given trainer always wears the same.
const npcSheet = (map, id) => {
  let h = 2166136261;
  for (const ch of `${map}:${id}`) { h ^= ch.charCodeAt(0); h = Math.imul(h, 16777619); }
  return new URL(`assets/characters/npc-${(h >>> 0) % NPC_VARIANTS}.png`, document.baseURI).href;
};
// Build the inner sprite body for an actor, themed to a sheet URL. Wrapped in a
// hop element so the walk-bounce (translateY) never collides with the body's
// scaleX facing mirror.
const actorBody = (sheet) => el('span', { class: 'ow-actor-hop' }, [
  el('span', { class: 'ow-actor-body sprite', style: `--sheet:url("${sheet}")` }),
]);

export class Overworld {
  // dex: engine Dex; world: bundle from loadWorld(); state: shared game state;
  // hooks: { onGrass, onTrainer, onGym, onMart, onNorth, onExit }
  constructor(dex, world, state, hooks = {}) {
    this.dex = dex;
    this.world = world;
    this.state = state;
    this.hooks = hooks;
    this.root = el('div', { class: 'overworld' });
    this.busy = false;
    this.held = null;       // currently-held direction (for continuous walk)
    this.stepping = false;  // a step is animating
    this.players = [];      // remote players for presence (Task 17)
    this.tileEls = [];      // grid cell elements, indexed y*W+x
    this.actorEls = new Map();
    this._onKeyDown = (e) => this.onKeyDown(e);
    this._onKeyUp = (e) => this.onKeyUp(e);
    this._onResize = () => this.layout();
  }

  // ---- lifecycle ---------------------------------------------------------
  mount() {
    this.buildDom();
    this.render();
    window.addEventListener('keydown', this._onKeyDown);
    window.addEventListener('keyup', this._onKeyUp);
    window.addEventListener('resize', this._onResize);
    this.layout();
    return this.root;
  }

  destroy() {
    window.removeEventListener('keydown', this._onKeyDown);
    window.removeEventListener('keyup', this._onKeyUp);
    window.removeEventListener('resize', this._onResize);
    this.held = null;
  }

  get map() { return this.world.mapById[this.state.map]; }

  // ---- DOM scaffold ------------------------------------------------------
  buildDom() {
    this.root.innerHTML = '';
    this.hud = {};

    // ---- top bar: [money · balls] ···· [badges] ···· [PC Box · Items · Exit]
    this.hud.money = el('span', { class: 'ow-money' });
    this.hud.balls = el('span', { class: 'ow-balls' });
    this.hud.badges = el('span', { class: 'ow-badges' });
    this.hud.maxlv = el('span', { class: 'ow-maxlv', title: 'Highest Pokémon level on this route' });
    const boxBtn = el('button', { class: 'ghost ow-btn', text: '💻 PC Box', onclick: () => this.runHook('onBox') });
    const itemsBtn = el('button', { class: 'ghost ow-btn', text: '🎒 Items', onclick: () => this.runHook('onItems') });
    const exit = el('button', { class: 'ghost ow-leave', text: '↩ Exit', onclick: () => this.hooks.onExit && this.hooks.onExit() });
    const topBar = el('div', { class: 'ow-hud ow-top' }, [
      el('div', { class: 'ow-hud-group ow-left' }, [this.hud.money, this.hud.balls]),
      el('div', { class: 'ow-hud-group ow-center' }, [this.hud.badges, this.hud.maxlv]),
      el('div', { class: 'ow-hud-group ow-right' }, [boxBtn, itemsBtn, exit]),
    ]);

    // ---- arena: tile stage + always-on party bar (+ transient toast)
    this.gridEl = el('div', { class: 'ow-grid' });
    this.structuresEl = el('div', { class: 'ow-structures' });
    this.actorsEl = el('div', { class: 'ow-actors' });
    this.stageEl = el('div', { class: 'ow-stage' }, [this.gridEl, this.structuresEl, this.actorsEl]);
    // Tapping a tile walks toward it / interacts (touch friendliness).
    this.stageEl.addEventListener('click', (e) => this.onStageClick(e));
    this.partyBarEl = el('div', { class: 'ow-party' });
    this.toastEl = el('div', { class: 'ow-toast' });
    this.arena = el('div', { class: 'ow-arena' }, [this.stageEl, this.partyBarEl, this.toastEl]);

    // ---- bottom bar: [Route N · Name · ⓘ Route · day] ···· [#code]
    this.hud.route = el('span', { class: 'ow-route-label' });
    this.hud.day = el('span', { class: 'ow-day' });
    const routeBtn = el('button', { class: 'ghost ow-route', text: 'ⓘ Route Info', onclick: () => this.openRouteInfo() });
    const codeChip = this.state.lobbyCode
      ? el('button', { class: 'ghost ow-code', title: 'Lobby code — click to copy', text: `#${this.state.lobbyCode}`,
          onclick: () => { try { navigator.clipboard.writeText(String(this.state.lobbyCode)); this.say(`Copied lobby code #${this.state.lobbyCode}`); } catch { /* ignore */ } } })
      : null;
    // Ephemeral chat: type + Enter sends a speech bubble to everyone on the map.
    this.chatInput = el('input', {
      class: 'ow-chat-input', type: 'text', maxlength: 120, placeholder: 'Press Enter to chat…',
      onkeydown: (e) => this.onChatKey(e),
    });
    const bottomBar = el('div', { class: 'ow-hud ow-bottom' }, [
      el('div', { class: 'ow-hud-group ow-left' }, [this.hud.route, routeBtn, this.hud.day]),
      this.chatInput,
      el('div', { class: 'ow-hud-group ow-right' }, [codeChip]),
    ]);

    this.root.append(el('div', { class: 'ow-frame' }, [topBar, this.arena, bottomBar]));
  }

  // ---- rendering ---------------------------------------------------------
  render() {
    const m = this.map;
    this.W = m.width; this.H = m.height;
    this.tiles = m.tiles.map((row) => row.split(''));
    this.renderHud();
    this.renderGrid();
    this.renderStructures();
    this.renderActors();
    this.renderPartyBar();
  }

  renderHud() {
    const m = this.map;
    const prog = this.world.progression.maps.find((p) => p.map === m.map);
    if (this.hud.route) this.hud.route.textContent = `Route ${m.map} · ${cap(m.theme)}`;
    if (this.hud.day) {
      if (this.state.mode === 'week') {
        const day = (this.state.dayIndex || 0) + 1;
        const of = this.state.weekLength || this.world.progression.mapCount;
        this.hud.day.textContent = this.state.weekLocked ? '🏁 Week over' : `☀ Day ${day}/${of}`;
        this.hud.day.classList.toggle('locked', !!this.state.weekLocked);
      } else this.hud.day.textContent = '';
    }
    const money = this.state.money ?? 0;
    this.hud.money.textContent = `₽${money.toLocaleString('en-US')}`;
    if (this.hud.balls) {
      // Catchable encounters remaining on THIS route (Poké Balls are free now).
      const setting = this.state.encounterSetting;
      const max = setting === 'infinite' ? Infinity : (Number(setting) || 10);
      const enc = this.state.encounters || {};
      const left = max === Infinity ? Infinity : (enc[m.map] != null ? enc[m.map] : max);
      const gb = (this.state.balls && this.state.balls.greatball) || 0;
      this.hud.balls.textContent = `◓ ${left === Infinity ? '∞' : left}${gb ? ` · GB×${gb}` : ''}`;
      this.hud.balls.title = `Catchable encounters left on this route${gb ? ` · ${gb} Great Ball${gb === 1 ? '' : 's'}` : ''}`;
    }
    const b = (this.state.badges && this.state.badges[m.map]) || {};
    const k = prog ? prog.kanto : 'Kanto';
    const j = prog ? prog.johto : 'Johto';
    this.hud.badges.innerHTML = '';
    this.hud.badges.append(
      el('span', { class: `ow-badge${b.kanto ? ' on' : ''}`, title: k, text: '◆' }),
      el('span', { class: `ow-badge${b.johto ? ' on' : ''}`, title: j, text: '◆' }),
    );
    if (this.hud.maxlv) {
      const maxLv = prog && prog.maxLevel;
      this.hud.maxlv.textContent = maxLv ? `Max Lv. ${maxLv}` : '';
    }
  }

  // Always-on team bar down the right of the stage. Shows each member (sprite /
  // name / level / types); a click opens that mon's summary (onPartyMon hook),
  // and slots can be dragged to reorder the party — the top slot is the lead
  // (party[0], who sends out first). Call after any party change to refresh.
  renderPartyBar() {
    if (!this.partyBarEl) return;
    const party = this.state.party || [];
    // Route level cap = this map's "Max Lv". Pokémon at/over it show a full,
    // frozen EXP bar (they resume gaining EXP on a higher-cap route).
    const prog = this.world.progression.maps.find((p) => p.map === this.state.map);
    const cap = prog ? (prog.maxLevel ?? prog.cap ?? 100) : 100;
    this.partyBarEl.innerHTML = '';
    this.partyBarEl.append(el('div', { class: 'ow-party-h', text: `Team ${party.length}/6` }));
    party.forEach((mon, i) => {
      const atCap = mon.level >= cap;
      const frac = atCap ? 1 : expFraction(mon);
      const sp = this.dex.getSpecies(mon.species);
      const name = mon.nickname || sp.name;
      const slot = el('div', {
        class: `ow-party-slot${mon.shiny ? ' shiny' : ''}${i === 0 ? ' lead' : ''}`,
        title: `${name} · Lv ${mon.level}${i === 0 ? ' · leads' : ''} — click for summary, drag to reorder`,
        draggable: 'true',
        onclick: () => { if (this._dragFrom == null) this.runHook('onPartyMon', i); },
        ondragstart: (e) => {
          this._dragFrom = i; slot.classList.add('dragging');
          e.dataTransfer.effectAllowed = 'move';
          try { e.dataTransfer.setData('text/plain', String(i)); } catch { /* ignore */ }
        },
        ondragend: () => { slot.classList.remove('dragging'); this._dragFrom = null; },
        ondragover: (e) => { if (this._dragFrom == null) return; e.preventDefault(); e.dataTransfer.dropEffect = 'move'; slot.classList.add('drag-over'); },
        ondragleave: () => slot.classList.remove('drag-over'),
        ondrop: (e) => { e.preventDefault(); slot.classList.remove('drag-over'); this.reorderParty(this._dragFrom, i); },
      }, [
        el('span', { class: 'ow-party-rank', text: `${i + 1}` }),
        el('img', { class: 'ow-party-sprite', src: spriteFront(sp.num, mon.shiny), alt: sp.name, draggable: 'false' }),
        el('div', { class: 'ow-party-info' }, [
          el('span', { class: 'ow-party-name', text: name + (mon.shiny ? ' ✦' : '') }),
          el('span', { class: 'ow-party-lv', text: `Lv ${mon.level}` }),
          el('div', { class: 'ow-party-types' }, sp.types.map((t) =>
            el('span', { class: 'ow-ptype', style: `background:${TYPE_COLORS[t] || '#888'}`, text: t }))),
        ]),
        el('div', { class: `ow-party-exp${atCap ? ' maxed' : ''}`, title: atCap ? `At this route's max level (Lv ${cap})` : `EXP: ${Math.round(frac * 100)}% to next level` }, [
          el('div', { class: 'ow-party-exp-fill', style: `width:${Math.round(frac * 100)}%` }),
        ]),
      ]);
      this.partyBarEl.append(slot);
    });
  }

  // Move party[from] to position `to` (drag-reorder from the team bar). The
  // resulting order is the battle order, so this can change the lead. Persists
  // via the host so the new order survives reloads / syncs to the lobby.
  reorderParty(from, to) {
    const p = this.state.party;
    if (from == null || from === to || from < 0 || to < 0 || from >= p.length || to >= p.length) return;
    const [mon] = p.splice(from, 1);
    p.splice(to, 0, mon);
    this.renderPartyBar();
    if (this.hooks.onPartyReorder) this.hooks.onPartyReorder(this);
  }

  renderGrid() {
    this.gridEl.style.gridTemplateColumns = `repeat(${this.W}, var(--tile))`;
    this.gridEl.innerHTML = '';
    this.tileEls = new Array(this.W * this.H);
    this.gridEl.classList.value = `ow-grid theme-${this.map.theme}`;
    for (let y = 0; y < this.H; y++) {
      for (let x = 0; x < this.W; x++) {
        const code = this.tiles[y][x];
        const cell = el('div', { class: `ow-tile ${tileClass(code)}` });
        if (code === NORTH) cell.append(el('span', { class: 'ow-arrow', text: '↑' }));
        // South gap doubles as the way back to the previous route (not on Route 1).
        if (code === SPAWN && this.state.map > 1) cell.append(el('span', { class: 'ow-arrow', text: '↓' }));
        this.gridEl.append(cell);
        this.tileEls[y * this.W + x] = cell;
      }
    }
  }

  // Building sprites overlay the grid: each is anchored to its door tile (the
  // bottom-center of a 3x3 footprint) and grows upward. A small sign sits over
  // the door so marts/gyms stay identifiable. Maps without buildings (the
  // arena) simply have no mart/gyms entries, so nothing is drawn.
  renderStructures() {
    this.structuresEl.innerHTML = '';
    const m = this.map;
    const add = (key, door, label) => {
      if (!door) return;
      const b = el('div', {
        class: 'ow-building',
        style: `--bx:${door.x - 1}; --by:${door.y - 2}; background-image:url("${BUILDING_SPRITES[key]}")`,
      }, [el('span', { class: 'ow-building-sign', text: label })]);
      this.structuresEl.append(b);
    };
    if (m.gyms) { add('kanto', m.gyms.kanto, 'GYM'); add('johto', m.gyms.johto, 'GYM'); }
    add('mart', m.mart, 'MART');
  }

  // NPC trainers + the player + remote players live on the actor overlay.
  renderActors() {
    this.actorsEl.innerHTML = '';
    this.actorEls.clear();
    const m = this.map;
    const beaten = this.beatenSet();
    for (const t of m.trainers) {
      const data = this.trainerData(t.id);
      const def = beaten.has(t.id);
      const a = el('div', {
        class: `ow-actor ow-npc face-${t.facing}${def ? ' beaten' : ''}`,
        title: data ? `${data.class} ${data.name}` : 'Trainer',
      }, [actorBody(npcSheet(m.map, t.id))]);
      this.placeActor(a, t.x, t.y);
      this.actorsEl.append(a);
      this.actorEls.set(`npc${t.id}`, a);
    }
    // player
    this.playerEl = el('div', { class: `ow-actor ow-player face-${this.state.facing || 'down'}` }, [actorBody(charSheet(this.state.character))]);
    this.placeActor(this.playerEl, this.state.x, this.state.y);
    this.actorsEl.append(this.playerEl);
    this.renderPlayers(this.players);
  }

  placeActor(node, x, y) {
    node.style.transform = `translate(calc(${x} * var(--tile)), calc(${y} * var(--tile)))`;
  }

  // Add or move a single remote player (Task 17). Reuses the existing actor so
  // its CSS transform transition animates the step; creates one on first sight.
  upsertPeer(p) {
    if (!p || p.id == null) return;
    const key = `rp${p.id}`;
    const idx = this.players.findIndex((q) => q.id === p.id);
    if (idx >= 0) this.players[idx] = { ...this.players[idx], ...p };
    else this.players.push({ ...p });
    const merged = this.players[idx >= 0 ? idx : this.players.length - 1];
    let a = this.actorEls.get(key);
    if (!a) {
      a = el('div', {
        class: `ow-actor ow-remote face-${merged.facing || 'down'}`, title: merged.name || 'Player',
        onclick: (e) => { e.stopPropagation(); this.hooks.onPlayerClick && this.hooks.onPlayerClick(merged); },
      }, [actorBody(charSheet(merged.character)), el('span', { class: 'ow-actor-tag', text: merged.name || '' })]);
      this.actorsEl.append(a);
      this.actorEls.set(key, a);
    } else {
      // Preserve the current walk-frame parity while updating facing.
      const fb = a.classList.contains('frame-b');
      a.className = `ow-actor ow-remote face-${merged.facing || 'down'}${fb ? ' frame-b' : ''}`;
      a.title = merged.name || 'Player';
    }
    // Bounce + toggle the walk frame on each move so remote players appear to stride.
    a.classList.toggle('frame-b');
    this.hop(a);
    this.placeActor(a, merged.x, merged.y);
    // Leaf burst when a known peer steps onto a grass tile (mirrors the local one).
    if (idx >= 0 && this.tiles && this.tiles[merged.y] && this.tiles[merged.y][merged.x] === GRASS) {
      this.grassRustle(merged.x, merged.y);
    }
  }

  removePeer(id) {
    const key = `rp${id}`;
    const a = this.actorEls.get(key);
    if (a) { a.remove(); this.actorEls.delete(key); }
    this.players = this.players.filter((q) => q.id !== id);
  }

  // Remote players for presence (Task 17). list: [{id,name,x,y,facing}]
  renderPlayers(list) {
    this.players = list || [];
    for (const [k, n] of this.actorEls) if (k.startsWith('rp')) { n.remove(); this.actorEls.delete(k); }
    for (const p of this.players) {
      const a = el('div', {
        class: `ow-actor ow-remote face-${p.facing || 'down'}`, title: p.name || 'Player',
        onclick: (e) => { e.stopPropagation(); this.hooks.onPlayerClick && this.hooks.onPlayerClick(p); },
      }, [actorBody(charSheet(p.character)), el('span', { class: 'ow-actor-tag', text: p.name || '' })]);
      this.placeActor(a, p.x, p.y);
      this.actorsEl.append(a);
      this.actorEls.set(`rp${p.id}`, a);
    }
  }

  // Compute the largest integer tile size that fits the available viewport,
  // leaving room for the party bar on the right and the top/bottom bars.
  layout() {
    const padX = 200, chromeY = 150; // party bar (~160) + page padding · top+bottom bars
    const availW = Math.max(120, window.innerWidth - padX);
    const availH = Math.max(120, window.innerHeight - chromeY);
    const tile = Math.max(14, Math.floor(Math.min(availW / this.W, availH / this.H)));
    this.tile = tile;
    this.root.style.setProperty('--tile', `${tile}px`);
    this.root.style.setProperty('--step-ms', `${STEP_MS}ms`); // walk glide duration
    this.stageEl.style.width = `${tile * this.W}px`;
    this.stageEl.style.height = `${tile * this.H}px`;
  }

  // ---- state helpers -----------------------------------------------------
  beatenSet() {
    const bt = this.state.beatenTrainers || (this.state.beatenTrainers = {});
    const arr = bt[this.state.map] || (bt[this.state.map] = []);
    return new Set(arr);
  }

  trainerData(id) {
    const list = this.world.trainers[this.state.map] || [];
    return list.find((t) => t.id === id) || null;
  }

  // Public: mark a trainer beaten and re-skin its NPC.
  markTrainerBeaten(id) {
    const bt = this.state.beatenTrainers || (this.state.beatenTrainers = {});
    const arr = bt[this.state.map] || (bt[this.state.map] = []);
    if (!arr.includes(id)) arr.push(id);
    const a = this.actorEls.get(`npc${id}`);
    if (a) a.classList.add('beaten');
  }

  // Public: record a gym badge and refresh the HUD.
  setBadge(side, won = true) {
    const b = this.state.badges || (this.state.badges = {});
    const m = b[this.state.map] || (b[this.state.map] = {});
    m[side] = won;
    this.renderHud();
  }

  // Public: switch to another map and place the player at an entry point.
  goToMap(mapId, entry = 'spawn') {
    this.state.map = mapId;
    const m = this.world.mapById[mapId];
    // 'north' = arriving from the route above: step in just below the north gap
    // (mirrors 'spawn', which sits just above the south gap).
    const pt = entry === 'north' ? { x: m.north.x, y: m.north.y + 1 } : (m[entry] || m.spawn);
    this.state.x = pt.x; this.state.y = pt.y;
    this.state.facing = entry === 'north' ? 'down' : 'up';
    this.render();
    this.layout();
  }

  // Transient feedback toast over the stage (replaces the old permanent log).
  say(text) {
    const t = this.toastEl;
    if (!t) return;
    clearTimeout(this._toastT);
    if (!text) { t.classList.remove('show'); t.textContent = ''; return; }
    t.textContent = text;
    t.classList.add('show');
    this._toastT = setTimeout(() => t.classList.remove('show'), 2600);
  }

  // A celebratory evolution toast: the evolved sprite + "X evolved into Y!" with
  // a golden glow. Queued so multiple evolutions play one after another.
  evoToast(fromName, toName, num) {
    (this._evoQueue || (this._evoQueue = [])).push({ fromName, toName, num });
    if (!this._evoPlaying) this._playEvoToast();
  }

  _playEvoToast() {
    const q = this._evoQueue || [];
    if (!q.length || !this.arena) { this._evoPlaying = false; return; }
    this._evoPlaying = true;
    const { fromName, toName, num } = q.shift();
    const card = el('div', { class: 'ow-evo-toast' }, [
      el('img', { class: 'ow-evo-sprite', src: spriteFront(num), alt: toName }),
      el('div', { class: 'ow-evo-text', html: `<span class="ow-evo-spark">✨</span> <b>${fromName}</b> evolved into <b>${toName}</b>!` }),
    ]);
    this.arena.append(card);
    void card.offsetWidth; card.classList.add('show');
    setTimeout(() => {
      card.classList.remove('show');
      setTimeout(() => { card.remove(); this._playEvoToast(); }, 400);
    }, 3000);
  }

  // Overlay listing the Pokémon that can appear in this route's grass: each is
  // shown as its sprite plus the chance of encountering it (rarity weight ÷ total).
  openRouteInfo() {
    if (this.routeOverlay) { this.closeRouteInfo(); return; }
    const list = (this.world.encounters[this.state.map] || []).slice();
    const total = list.reduce((s, e) => s + e.weight, 0) || 1;
    list.sort((a, b) => b.weight - a.weight);
    const cells = list.map((e) => {
      const pct = (100 * e.weight / total);
      const num = e.num != null ? e.num : this.dex.getSpecies(e.species).num;
      return el('div', { class: `ri-cell rar-${e.rarity}`, title: `${cap(e.rarity)} · ${pct.toFixed(1)}%` }, [
        el('img', { class: 'ri-sprite', src: spriteFront(num), alt: '' }),
        el('span', { class: 'ri-pct', text: `${pct.toFixed(1)}%` }),
      ]);
    });
    const panel = el('div', { class: 'panel ri-panel' }, [
      el('div', { class: 'ri-head' }, [
        el('h3', { text: `Route ${this.state.map} — Wild Pokémon` }),
        el('button', { class: 'ghost', text: '✕', onclick: () => this.closeRouteInfo() }),
      ]),
      el('div', { class: 'ri-list' }, cells),
      el('div', { class: 'ri-legend', text: 'Encounter chance per step in tall grass.' }),
    ]);
    this.routeOverlay = el('div', { class: 'ow-overlay', onclick: (e) => { if (e.target === this.routeOverlay) this.closeRouteInfo(); } }, [panel]);
    this.root.append(this.routeOverlay);
  }

  closeRouteInfo() { if (this.routeOverlay) { this.routeOverlay.remove(); this.routeOverlay = null; } }

  // ---- input -------------------------------------------------------------
  onKeyDown(e) {
    // While typing in any field (the chat box), don't drive movement.
    if (e.target && (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA' || e.target.isContentEditable)) return;
    if (e.key === 'Enter') { e.preventDefault(); if (this.chatInput) this.chatInput.focus(); return; } // open chat
    const dir = KEY_DIR[e.key];
    if (!dir) return;
    e.preventDefault();
    this.held = dir;
    this.pump();
  }

  onKeyUp(e) {
    const dir = KEY_DIR[e.key];
    if (dir && this.held === dir) this.held = null;
  }

  // Chat box keys: Enter sends (and the bubble shows for everyone on the map),
  // Escape clears + defocuses. stopPropagation keeps these out of movement.
  onChatKey(e) {
    e.stopPropagation();
    if (e.key === 'Enter') {
      const text = this.chatInput.value.trim();
      this.chatInput.value = '';
      if (text) this.sendChat(text);
      this.chatInput.blur();
    } else if (e.key === 'Escape') {
      this.chatInput.value = '';
      this.chatInput.blur();
    }
  }

  // Send a chat line: show our own bubble immediately, then fan out to peers.
  sendChat(text) {
    this.chatBubble(this.playerEl, text);
    if (this.hooks.onChat) this.hooks.onChat(text);
  }

  // Show a peer's chat bubble (called when a 'chat' push arrives).
  peerChat(id, text) {
    const a = this.actorEls.get(`rp${id}`);
    if (a) this.chatBubble(a, text);
  }

  // A speech bubble above an actor that fades and removes itself — no chat log.
  chatBubble(actorEl, text) {
    if (!actorEl) return;
    const old = actorEl.querySelector('.ow-chat-bubble');
    if (old) old.remove();
    const bubble = el('div', { class: 'ow-chat-bubble', text });
    actorEl.append(bubble);
    setTimeout(() => bubble.classList.add('fading'), 3200);
    setTimeout(() => bubble.remove(), 4000);
  }

  onStageClick(e) {
    if (this.busy || this.stepping) return;
    const rect = this.stageEl.getBoundingClientRect();
    const tx = Math.floor((e.clientX - rect.left) / this.tile);
    const ty = Math.floor((e.clientY - rect.top) / this.tile);
    if (tx < 0 || ty < 0 || tx >= this.W || ty >= this.H) return;
    // Step one tile toward the clicked cell (whichever axis is farther).
    const dx = tx - this.state.x, dy = ty - this.state.y;
    if (dx === 0 && dy === 0) return;
    const dir = Math.abs(dx) >= Math.abs(dy) ? (dx > 0 ? 'right' : 'left') : (dy > 0 ? 'down' : 'up');
    this.held = null;
    this.tryStep(dir).then(() => this.idlePose());
  }

  // Continuous-walk pump: steps while a direction is held.
  async pump() {
    if (this.busy || this.stepping) return;
    while (this.held && !this.busy) {
      const dir = this.held;
      const moved = await this.tryStep(dir);
      if (!moved) break; // bumped a wall/interactable — stop the auto-walk
    }
    this.idlePose();
  }

  // Settle the player on the standing (frame A) pose when not walking.
  idlePose() {
    this._walk = false;
    if (this.playerEl) this.playerEl.classList.remove('frame-b');
  }

  // Attempt to move/interact one tile in `dir`. Returns true if the player
  // actually moved (so the pump can continue), false otherwise.
  async tryStep(dir) {
    if (this.busy || this.stepping) return false;
    this.state.facing = dir;
    if (this.playerEl) this.playerEl.className = `ow-actor ow-player face-${dir}${this._walk ? ' frame-b' : ''}`;
    const { dx, dy } = DIRS[dir];
    const nx = this.state.x + dx, ny = this.state.y + dy;
    if (nx < 0 || ny < 0 || nx >= this.W || ny >= this.H) return false;
    const code = this.tiles[ny][nx];

    // Interactables block the tile but trigger their hook on bump.
    if (code === TRAINER) { await this.interactTrainer(nx, ny); return false; }
    if (code === MART) { await this.runHook('onMart'); return false; }
    if (code === GYM_K) { await this.interactGym('kanto'); return false; }
    if (code === GYM_J) { await this.interactGym('johto'); return false; }
    if (code === WALL || !WALKABLE.has(code)) return false;

    // Walkable — animate the step.
    await this.moveTo(nx, ny);
    if (code === GRASS) this.grassRustle(nx, ny); // leaf burst so tall grass reads
    if (this.hooks.onStep) this.hooks.onStep(this); // debounced position save

    // Post-move triggers.
    if (code === GRASS) await this.runHook('onGrass');
    else if (code === NORTH) await this.interactNorth();
    else if (code === SPAWN) await this.runHook('onSouth'); // south gap → previous route
    return true;
  }

  // A short leaf-burst at tile (x,y) — played when someone steps onto tall grass
  // so it's obvious they're moving through it. Self-removing; no state kept.
  grassRustle(x, y) {
    if (!this.actorsEl) return;
    const fx = el('div', { class: 'ow-grass-fx' });
    const n = 6;
    for (let i = 0; i < n; i++) {
      const ang = (i / n) * Math.PI * 2 + (Math.random() * 0.7 - 0.35);
      const dist = 9 + Math.random() * 8;
      const dx = Math.cos(ang) * dist;
      const dy = Math.sin(ang) * dist - 4; // bias upward
      fx.append(el('span', {
        class: 'ow-leaf',
        style: `--dx:${dx.toFixed(1)}px; --dy:${dy.toFixed(1)}px; --rot:${(Math.random() * 280 - 140) | 0}deg`,
      }));
    }
    this.placeActor(fx, x, y);
    this.actorsEl.append(fx);
    setTimeout(() => fx.remove(), 620);
  }

  moveTo(x, y) {
    return new Promise((resolve) => {
      this.stepping = true;
      // Advance the walk cycle so the player's legs alternate each tile.
      this._walk = !this._walk;
      if (this.playerEl) { this.playerEl.classList.toggle('frame-b', this._walk); this.hop(this.playerEl); }
      this.state.x = x; this.state.y = y;
      this.placeActor(this.playerEl, x, y);
      setTimeout(() => { this.stepping = false; resolve(); }, STEP_MS);
    });
  }

  // Re-trigger a single bounce on an actor's hop wrapper. Setting animation to
  // 'none', forcing a reflow, then re-setting it restarts the keyframes so the
  // hop fires fresh on every step (CSS won't replay an unchanged animation).
  hop(actor) {
    const h = actor && actor.querySelector('.ow-actor-hop');
    if (!h) return;
    h.style.animation = 'none';
    void h.offsetWidth;
    h.style.animation = `ow-hop ${HOP_MS}ms ease-out`;
  }

  // ---- interactions ------------------------------------------------------
  async interactTrainer(x, y) {
    const t = this.map.trainers.find((tt) => tt.x === x && tt.y === y);
    if (!t) return;
    if (this.beatenSet().has(t.id)) { this.say('That trainer has already been defeated.'); return; }
    const won = await this.runHook('onTrainer', this.trainerData(t.id), t);
    if (won) { this.markTrainerBeaten(t.id); if (this.hooks.onProgress) this.hooks.onProgress(this); }
  }

  async interactGym(side) {
    const won = await this.runHook('onGym', side);
    if (won) { this.setBadge(side, true); if (this.hooks.onProgress) this.hooks.onProgress(this); }
  }

  async interactNorth() {
    await this.runHook('onNorth');
  }

  // Run a hook with input locked; tolerate missing hooks.
  async runHook(name, ...args) {
    const fn = this.hooks[name];
    if (typeof fn !== 'function') return undefined;
    this.busy = true;
    this.held = null;
    try {
      return await fn(this, ...args);
    } finally {
      this.busy = false;
    }
  }
}

// ---- helpers -------------------------------------------------------------
function tileClass(code) {
  switch (code) {
    case WALL: return 'tile-wall';
    case GRASS: return 'tile-grass';
    case MART: return 'tile-mart';
    case GYM_K: return 'tile-gym tile-gym-k';
    case GYM_J: return 'tile-gym tile-gym-j';
    case NORTH: return 'tile-north';
    case SPAWN: return 'tile-spawn';
    case BUILDING: return 'tile-floor tile-building';
    case TRAINER: return 'tile-floor tile-trainer';
    default: return 'tile-floor';
  }
}
function cap(s) { return (s || '').charAt(0).toUpperCase() + (s || '').slice(1); }
